Repository blue-oil/blueoil, pull requests merged in 2019-07, with the labels that each got.

#336 Show progressbar during training
  lmnet/executor/train.py
Labels: enhancement

#353 Optimize for AArch64/AArch32
  dlk/python/dlk/templates/CMakeLists.txt
  dlk/python/dlk/templates/Makefile.tpl
  dlk/python/dlk/templates/include/func/impl/pack_16bit.h
  dlk/python/dlk/templates/src/func/arm_neon/batch_normalization.cpp
  dlk/python/dlk/templates/src/func/impl/arm_neon/apply_thresholds.cpp
  dlk/python/dlk/templates/src/func/impl/arm_neon/pack_16bit.cpp
  dlk/python/dlk/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  dlk/python/dlk/templates/src/func/impl/generic/apply_thresholds.cpp
  dlk/python/dlk/templates/src/func/impl/generic/pack_16bit.cpp
  dlk/python/dlk/templates/src/pack_input_to_qwords.cpp
Labels: enhancement

#359 More optimize for AArch32/AArch64
  dlk/python/dlk/templates/CMakeLists.txt
  dlk/python/dlk/templates/cmake/toolchain/linux_arm.cmake
  dlk/python/dlk/templates/include/func/extract_image_patches.h
  dlk/python/dlk/templates/include/func/impl/apply_thresholds.h
  dlk/python/dlk/templates/src/func/impl/arm_neon/apply_thresholds.cpp
  dlk/python/dlk/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  dlk/python/dlk/templates/src/func/lookup.cpp
Labels: enhancement

#357 Introduce Buildkite to Blueoil CI
  .buildkite/blueoil-pipeline.yml
  .buildkite/dlk-pipeline.yml
  .buildkite/lmnet-pipeline.yml
  README.md
  tests/README.md
Labels: CI: auto-run

#352 Enable Resume Training for Object Detection
  blueoil/templates/lmnet/object_detection.tpl.py
  dlk/examples/object_detection/fyolo_quantize_17_v14_some_1x1_wide_pact_add_conv/config.yaml
  dlk/examples/object_detection/fyolo_quantize_4_v4/config.yaml
  dlk/examples/object_detection/widerface_320/config.yaml
  dlk/examples/object_detection/widerface_v5/config.yaml
  lmnet/configs/core/object_detection/lm_fyolo_bdd100k.py
  lmnet/configs/core/object_detection/lm_fyolo_quantize_pascalvoc_2007_2012.py
  lmnet/configs/core/object_detection/yolo_v2_openimagesv4.py
  lmnet/configs/core/object_detection/yolo_v2_pascalvoc_2007_2012.py
  lmnet/configs/core/object_detection/yolo_v2_quantize_pascalvoc_2007_2012.py
  lmnet/configs/example/object_detection.py
  lmnet/configs/example/object_detection.yaml
  lmnet/executor/train.py
  lmnet/lmnet/networks/object_detection/yolo_v2.py
  lmnet/tests/lmnet_tests/networks_tests/object_detection_tests/test_yolo_v2.py
Labels: CI: auto-run

#365 Optimize for x86 AVX
  dlk/python/dlk/templates/Makefile.tpl
  dlk/python/dlk/templates/include/func/quantized_conv2d.h
  dlk/python/dlk/templates/include/tensor_view.h
  dlk/python/dlk/templates/manual/consts/input.tpl.cpp
  dlk/python/dlk/templates/manual/consts/input.tpl.h
  dlk/python/dlk/templates/src/func/impl/x86_avx/apply_thresholds.cpp
  dlk/python/dlk/templates/src/func/impl/x86_avx/pack_16bit.cpp
  dlk/python/dlk/templates/src/func/impl/x86_avx/quantized_conv2d_tiling.cpp
Labels: CI: auto-run, enhancement

#371 Update to v0.9.0
  setup.cfg
Labels: CI: auto-run

#360 Time measurement reporting tidy-up.
  dlk/python/dlk/templates/src/time_measurement.cpp
  dlk/tests/test_binary.py
Labels: CI: auto-run

#358 Documentation for time measurement.
  docs/usage/index.rst
  docs/usage/timing.md
Labels: CI: auto-run

#373 More optimization for x86 AVX
  dlk/python/dlk/templates/include/func/extract_image_patches.h
  dlk/python/dlk/templates/src/func/impl/x86_avx/apply_thresholds.cpp
  dlk/python/dlk/templates/src/func/impl/x86_avx/quantized_conv2d_tiling.cpp
  dlk/python/dlk/templates/src/func/lookup.cpp
  dlk/python/dlk/templates/src/network.tpl.cpp
Labels: CI: auto-run, enhancement

#344 Fix Makefile.tpl
  dlk/python/dlk/templates/Makefile.tpl
Labels: CI: auto-run

#376 Remove jenkins
  Makefile
  README.md
  dlk/README.md
  lmnet/CONTRIBUTING.md
  lmnet/README.md
  tests/README.md
Labels: CI: auto-run
