Repository blue-oil/blueoil, pull requests merged in 2019-08, with the labels that each got.

#379 Fix queue compatibilty in usb camera demo
  output_template/python/usb_camera_demo.py
Labels: CI: auto-run, bug

#370 Implemented TFDSObjectDetection class
  lmnet/lmnet/datasets/dataset_iterator.py
  lmnet/lmnet/datasets/tfds.py
Labels: CI: auto-run

#380 update_to_v0.10.0
  setup.cfg
Labels: CI: auto-run

#253 runtime post process implementation
  runtime/CMakeLists.txt
  runtime/CPPLINT.cfg
  runtime/README.md
  runtime/examples/run.cpp
  runtime/include/blueoil.hpp
  runtime/include/blueoil_data_processor.hpp
  runtime/include/blueoil_image.hpp
  runtime/include/blueoil_opencv.hpp
  runtime/src/blueoil.cpp
  runtime/src/blueoil_data_processor.cpp
  runtime/src/blueoil_image.cpp
  runtime/src/blueoil_opencv.cpp
  runtime/test/CMakeLists.txt
  runtime/test/network_dummy.cpp
  runtime/test/test_data_processor.cpp
  runtime/test/test_image.cpp
  runtime/test/test_opencv.cpp
  runtime/test/test_resize.cpp
  runtime/test/test_tensor.cpp
  runtime/test/test_util.cpp
  runtime/test/test_util.hpp
Labels: CI: auto-run, enhancement

#382 Change CI Badge Branch to master
  README.md
Labels: CI: auto-run, documentation

#385 Show only rank 0 progbar
  lmnet/executor/train.py
Labels: CI: auto-run

#378 Support resize_nearest_neighbor op
  dlk/python/dlk/core/operators.py
  dlk/python/dlk/plugins/tf.py
  dlk/python/dlk/templates/include/func/resize_nearest_neighbor.h
  dlk/python/dlk/templates/src/network.tpl.cpp
Labels: CI: auto-run

#384 call flush method of a writer after the writer wrote summary data
  lmnet/executor/train.py
Labels: CI: auto-run

#381 Update rbf and preloader
  output_template/fpga/preloader-mkpimage.bin
  output_template/fpga/soc_system.rbf
Labels: CI: auto-run, enhancement

#389 Add FAQ section and improve installation and tutorial section of documentation
  docs/faq/faq.md
  docs/faq/index.rst
  docs/index.rst
  docs/install/install.md
  docs/tutorial/run_fpga.md
Labels: CI: auto-run, documentation

#388 Fix reference doc links
  lmnet/lmnet/data_augmentor.py
Labels: CI: auto-run, documentation

#394 use tf.cast instead of tf.to_int32, etc
  lmnet/lmnet/metrics/mean_average_precision.py
  lmnet/lmnet/metrics/metrics.py
  lmnet/lmnet/networks/classification/base.py
  lmnet/lmnet/networks/classification/resnet.py
  lmnet/lmnet/networks/lmnet_multi.py
  lmnet/lmnet/networks/object_detection/yolo_v1.py
  lmnet/lmnet/networks/object_detection/yolo_v2.py
  lmnet/lmnet/networks/segmentation/base.py
  lmnet/lmnet/quantizations/ternary.py
Labels: CI: auto-run

#383 Remove unnecessary summary from export.py and profile_model.py
  lmnet/executor/export.py
  lmnet/executor/profile_model.py
Labels: CI: auto-run

#392 Custom TFDS Builder / Executor Script
  lmnet/executor/build_tfds.py
  lmnet/executor/evaluate.py
  lmnet/executor/train.py
  lmnet/executor/tune_ray.py
  lmnet/lmnet/datasets/tfds.py
  lmnet/lmnet/utils/tfds_builders/classification.py
  lmnet/lmnet/utils/tfds_builders/object_detection.py
  lmnet/tests/executor_tests/test_build_tfds.py
  lmnet/tests/fixtures/configs/for_build_tfds_classification.py
  lmnet/tests/fixtures/configs/for_build_tfds_object_detection.py
Labels: CI: auto-run

#400 Fix round
  dlk/python/dlk/core/operators.py
  lmnet/lmnet/quantizations/linear.py
Labels: CI: auto-run
