Repository blue-oil/blueoil, pull requests merged in 2019-04, with the labels that each got.

#194 Create Makefile and unify test commands in it
  .dockerignore
  .jenkins/README.md
  .jenkins/test_blueoil.sh
  .jenkins/test_dlk.sh
  .jenkins/test_lmnet.sh
  Makefile
  README.md
  blueoil.sh
  docker/Dockerfile
  docker_build.sh
  docs/install/install.md
  lmnet/.gitignore
  lmnet/lmnet/__init__.py
  tests/README.md
Labels: enhancement

#217 Implement packed data type
  dlk/python/dlk/templates/CMakeLists.txt
  dlk/python/dlk/templates/Makefile.tpl
  dlk/python/dlk/templates/include/func/impl/pop_count.h
  dlk/python/dlk/templates/include/global.tpl.h
  dlk/python/dlk/templates/src/func/impl/arm_neon/pop_count.cpp
  dlk/python/dlk/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  dlk/python/dlk/templates/src/func/impl/generic/pop_count.cpp
  dlk/python/dlk/templates/src/func/impl/quantized_conv2d_dim2col.cpp
  dlk/python/dlk/templates/src/matrix/arm_neon/quantized_multiplication.cpp
  dlk/python/dlk/templates/src/matrix/generic/quantized_multiplication.cpp
  dlk/python/dlk/templates/src/pack_input_to_qwords.cpp
Labels: enhancement

#224 Implement SegnetBase class
  lmnet/lmnet/networks/segmentation/base.py
  lmnet/lmnet/networks/segmentation/lm_segnet_v0.py
  lmnet/lmnet/networks/segmentation/lm_segnet_v1.py
Labels: enhancement

#225 [LMBiSeNet] Implement LMBiSeNet
  lmnet/configs/core/segmentation/lm_bisenet_quantize_camvid.py
  lmnet/lmnet/networks/segmentation/lm_bisenet.py
  lmnet/lmnet/post_processor.py
  lmnet/tests/lmnet_tests/networks_tests/segmentation_tests/test_lm_bisenet.py
Labels: enhancement

#222 Fix condition
  dlk/python/dlk/templates/src/matrix/generic/quantized_multiplication.cpp
Labels: bug

#230 Change default model in usb camera demo
  output_template/python/usb_camera_demo.py
Labels: bug

#202 update TensorFlow version
  dlk/setup.py
  docker/Dockerfile
  lmnet/cpu.requirements.txt
  lmnet/dockerfiles/gpu.Dockerfile
  lmnet/dockerfiles/multi-gpu.Dockerfile
  lmnet/executor/output_event.py
  lmnet/gpu.requirements.txt
  lmnet/lmnet/metrics/mean_average_precision.py
Labels: enhancement

#155 Semantic segmentation python demo
  lmnet/lmnet/common.py
  output_template/python/usb_camera_demo.py
Labels: enhancement

#226 Use QuantizedPacked for kernel
  dlk/python/dlk/core/config.py
  dlk/python/dlk/core/data_types.py
  dlk/python/dlk/core/optimizer.py
  dlk/python/dlk/core/params.py
  dlk/python/dlk/templates/CMakeLists.txt
  dlk/python/dlk/templates/Makefile.tpl
  dlk/python/dlk/templates/include/de10_nano.h
  dlk/python/dlk/templates/include/func/impl/quantized_conv2d_dim2col.h
  dlk/python/dlk/templates/include/func/impl/quantized_conv2d_kn2row.h
  dlk/python/dlk/templates/include/func/impl/quantized_conv2d_tiling.h
  dlk/python/dlk/templates/include/func/quantized_conv2d.h
  dlk/python/dlk/templates/include/global.tpl.h
  dlk/python/dlk/templates/include/matrix/quantized_multiplication.h
  dlk/python/dlk/templates/manual/consts/input.tpl.cpp
  dlk/python/dlk/templates/manual/consts/input.tpl.h
  dlk/python/dlk/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  dlk/python/dlk/templates/src/func/impl/fpga/quantized_conv2d_kn2row.cpp
  dlk/python/dlk/templates/src/func/impl/generic/quantized_conv2d_kn2row.cpp
  dlk/python/dlk/templates/src/func/impl/quantized_conv2d_dim2col.cpp
  dlk/python/dlk/templates/src/func/quantized_conv2d.cpp
  dlk/python/dlk/templates/src/matrix/arm_neon/quantized_multiplication.cpp
  dlk/python/dlk/templates/src/matrix/generic/quantized_multiplication.cpp
  dlk/tests/test_optimizer.py
Labels: enhancement

#237 fix typo: s/pyhon/python/
  blueoil.sh
  lmnet/lmnet/networks/object_detection/yolo_v1.py
  lmnet/lmnet/networks/object_detection/yolo_v2.py
Labels: bug

#239 Update TensorFlow, CUDA and OepnCV version in README
  output_template/python/README.md
Labels: documentation

#238 Fix MaxPool implementation
  dlk/python/dlk/core/operators.py
  dlk/python/dlk/core/view.py
  dlk/python/dlk/templates/include/func/max_pool.h
  dlk/python/dlk/templates/src/func/max_pool.cpp
Labels: bug
