Repository blue-oil/blueoil, pull requests merged in 2019-03, with the labels that each got.

#131 Improve performance by utilizing cache locality
  dlk/python/dlk/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
Labels: enhancement

#176 [Semantic Segmentation] Add CamVid fixture dataset and Documentation
  docs/usage/dataset.md
  lmnet/tests/fixtures/datasets/camvid/train.txt
  lmnet/tests/fixtures/datasets/camvid/train/0001TP_006690.png
  lmnet/tests/fixtures/datasets/camvid/train/0001TP_006720.png
  lmnet/tests/fixtures/datasets/camvid/train/0001TP_006750.png
  lmnet/tests/fixtures/datasets/camvid/train/0001TP_006780.png
  lmnet/tests/fixtures/datasets/camvid/train/0001TP_006810.png
  lmnet/tests/fixtures/datasets/camvid/trainannot/0001TP_006690.png
  lmnet/tests/fixtures/datasets/camvid/trainannot/0001TP_006720.png
  lmnet/tests/fixtures/datasets/camvid/trainannot/0001TP_006750.png
  lmnet/tests/fixtures/datasets/camvid/trainannot/0001TP_006780.png
  lmnet/tests/fixtures/datasets/camvid/trainannot/0001TP_006810.png
  lmnet/tests/fixtures/datasets/camvid/val.txt
  lmnet/tests/fixtures/datasets/camvid/val/0016E5_07959.png
  lmnet/tests/fixtures/datasets/camvid/val/0016E5_07961.png
  lmnet/tests/fixtures/datasets/camvid/val/0016E5_07963.png
  lmnet/tests/fixtures/datasets/camvid/val/0016E5_07965.png
  lmnet/tests/fixtures/datasets/camvid/val/0016E5_07967.png
  lmnet/tests/fixtures/datasets/camvid/valannot/0016E5_07959.png
  lmnet/tests/fixtures/datasets/camvid/valannot/0016E5_07961.png
  lmnet/tests/fixtures/datasets/camvid/valannot/0016E5_07963.png
  lmnet/tests/fixtures/datasets/camvid/valannot/0016E5_07965.png
  lmnet/tests/fixtures/datasets/camvid/valannot/0016E5_07967.png
  lmnet/tests/fixtures/datasets/camvid_custom/label_colors.txt
  lmnet/tests/fixtures/datasets/camvid_custom/train.txt
  lmnet/tests/fixtures/datasets/camvid_custom/train/0001TP_006690.png
  lmnet/tests/fixtures/datasets/camvid_custom/train/0001TP_006720.png
  lmnet/tests/fixtures/datasets/camvid_custom/train/0001TP_006750.png
  lmnet/tests/fixtures/datasets/camvid_custom/train/0001TP_006780.png
  lmnet/tests/fixtures/datasets/camvid_custom/train/0001TP_006810.png
  lmnet/tests/fixtures/datasets/camvid_custom/trainannot/0001TP_006690.png
  lmnet/tests/fixtures/datasets/camvid_custom/trainannot/0001TP_006720.png
  lmnet/tests/fixtures/datasets/camvid_custom/trainannot/0001TP_006750.png
  lmnet/tests/fixtures/datasets/camvid_custom/trainannot/0001TP_006780.png
  lmnet/tests/fixtures/datasets/camvid_custom/trainannot/0001TP_006810.png
  lmnet/tests/fixtures/datasets/camvid_custom/val.txt
  lmnet/tests/fixtures/datasets/camvid_custom/val/0016E5_07959.png
  lmnet/tests/fixtures/datasets/camvid_custom/val/0016E5_07961.png
  lmnet/tests/fixtures/datasets/camvid_custom/val/0016E5_07963.png
  lmnet/tests/fixtures/datasets/camvid_custom/val/0016E5_07965.png
  lmnet/tests/fixtures/datasets/camvid_custom/val/0016E5_07967.png
  lmnet/tests/fixtures/datasets/camvid_custom/valannot/0016E5_07959.png
  lmnet/tests/fixtures/datasets/camvid_custom/valannot/0016E5_07961.png
  lmnet/tests/fixtures/datasets/camvid_custom/valannot/0016E5_07963.png
  lmnet/tests/fixtures/datasets/camvid_custom/valannot/0016E5_07965.png
  lmnet/tests/fixtures/datasets/camvid_custom/valannot/0016E5_07967.png
Labels: documentation, enhancement

#144 Output GPU Inference Model Template
  blueoil/blueoil_convert.py
  docs/tutorial/image_cls.md
  docs/tutorial/image_det.md
  docs/tutorial/run_fpga.md
  output_template/python/README.md
  output_template/python/lmnet/tensorflow_graph_runner.py
  output_template/python/lmnet/utils/demo.py
  output_template/python/run.py
  output_template/python/usb_camera_demo.py
Labels: enhancement

#166 Implement SimpleDatasetReader
  lmnet/lmnet/datasets/dataset_iterator.py
  lmnet/tests/lmnet_tests/datasets_tests/test_dataset_iterator.py
Labels: enhancement

#188 Add General Purpose Color Map
  docs/_static/color_map.png
  lmnet/lmnet/common.py
Labels: enhancement

#189 [Semantic Segmentation] Change CamvidCustom dataset format
  docs/usage/dataset.md
  lmnet/tests/fixtures/datasets/camvid_custom/label_colors.txt
  lmnet/tests/fixtures/datasets/camvid_custom/labels.txt
Labels: enhancement

#157 [WIP] Fix pack_input_to_qwords
  dlk/python/dlk/templates/src/pack_input_to_qwords.cpp
Labels: bug

#180 [Semantic Segmentation] Add Interface for Blueoil
  blueoil/blueoil_init.py
  blueoil/generate_lmnet_config.py
  blueoil/templates/lmnet/semantic_segmentation.tpl.py
  blueoil_test.sh
  lmnet/executor/train.py
  lmnet/lmnet/networks/segmentation/base.py
  output_template/python/lmnet/utils/output.py
  tests/config/camvid_custom_semantic_segmentation.yml
  tests/config/camvid_custom_semantic_segmentation_has_validation.yml
  tests/config/make_yml_config.py
Labels: enhancement

#174 [Semantic Segmentation] Add Tutorial
  docs/_static/camvid.jpg
  docs/_static/semantic_segmentation_iou.png
  docs/_static/semantic_segmentation_loss.png
  docs/_static/semantic_segmentation_output.png
  docs/_static/semantic_segmentation_overwrap.png
  docs/tutorial/image_cls.md
  docs/tutorial/image_seg.md
Labels: documentation

#198 Save blueoil config yaml
  blueoil/blueoil_train.py
Labels: enhancement

#204 Fix #203. Change color to tuple from list to fix run.py error
  lmnet/lmnet/common.py
  lmnet/tests/lmnet_tests/test_common.py
Labels: bug
