Repository blue-oil/blueoil, pull requests merged in 2020-05, with the labels that each got.

#1016 Move support ops to the end of converter document part
  docs/converter/index.rst
Labels: CI: auto-run, documentation

#1015 Update documents to follow latest Makefile
  docs/converter/archive_file.md
  docs/converter/shared_library.md
Labels: CI: auto-run

#1014 Add specification to blueoil document index.
  docs/index.rst
  docs/specification/index.rst
Labels: CI: auto-run, documentation

#1012 Remove "network" and "dataset" args from train end evaluate command
  blueoil/cmd/evaluate.py
  blueoil/cmd/train.py
  blueoil/generate_lmnet_config.py
  blueoil/utils/module_loader.py
  docs/usage/evaluate.md
  tests/unit/executor_tests/test_build_tfds.py
  tests/unit/executor_tests/test_export.py
  tests/unit/executor_tests/test_predict.py
  tests/unit/executor_tests/test_profile.py
  tests/unit/executor_tests/test_train.py
Labels: CI: auto-run

#1009 Remove _init_flag from environment module
  blueoil/environment.py
  tests/e2e/conftest.py
Labels: CI: auto-run

#1010 Remove unused global variables in environment module
  blueoil/environment.py
Labels: CI: auto-run

#1019 Remove first result from measurement
  output_template/python/run.py
Labels: CI: auto-run

#1024 Update python patch version and setup.cfg
  docker/Dockerfile
  setup.cfg
Labels: CI: auto-run

#1023 Install liblzma-dev in docker image
  docker/Dockerfile
Labels: CI: auto-run

#1022 Replace deprecated `np.asscalar()` with `np.ndarray.item()`
  blueoil/converter/core/operators.py
Labels: CI: auto-run

#915 Apply tf_upgrade_v2 for quantizations
  blueoil/quantizations/linear.py
  blueoil/quantizations/ternary.py
Labels: CI: auto-run

#1025 Remove deprecated properties from dataset class
  blueoil/datasets/bdd100k.py
  blueoil/datasets/dataset_iterator.py
  blueoil/datasets/delta_mark.py
  blueoil/datasets/image_folder.py
  blueoil/datasets/open_images_v4.py
  blueoil/datasets/pascalvoc_2007_2012.py
  blueoil/datasets/widerface.py
Labels: CI: auto-run

#1027 Optimize binary operation for converter runtime
  blueoil/converter/templates/include/func/impl/binary_op.h
Labels: CI: auto-run, enhancement

#1032 Fix image_keypoint_detection tutorial document typo
  docs/tutorial/image_keypoint_detection.md
Labels: CI: auto-run, documentation

#1030 Update (C++ inference) runtime documents
  runtime/README.md
Labels: CI: auto-run, documentation

#1031 Add PerImageStandardization compatibility in (C++ inference) runtime
  runtime/include/blueoil_data_processor.hpp
  runtime/src/blueoil.cpp
Labels: CI: auto-run

#1038 Add documentation about png usage in C++ runtime
  runtime/README.md
Labels: CI: auto-run, documentation

#1037 Add C++ runtime unit test (DivideBy255 and PerImageStandardization)
  runtime/test/test_data_processor.cpp
Labels: CI: auto-run

#1040 Remove unused address definitions
  blueoil/converter/templates/include/de10_nano.h
  blueoil/converter/templates/include/global.tpl.h
Labels: CI: auto-run

#1041 Delete unused test directory
  blueoil/converter/templates/test/CMakeLists.txt
  blueoil/converter/templates/test/testBuffer/CMakeLists.txt
  blueoil/converter/templates/test/testBuffer/main.cpp
  blueoil/converter/templates/test/testBuffer/testBuffer.cpp
Labels: CI: auto-run

#1044 Update setup.cfg to v0.23.0
  setup.cfg
Labels: CI: auto-run

#1054 Remove unused inheritance
  blueoil/converter/core/data_types.py
Labels: CI: auto-run

#1048 Fix bug with disabling cache on FPGA
  blueoil/converter/templates/include/dma_buffer.h
Labels: CI: auto-run

#1049 Added "data_dir" and "output_dir" options to the command.
  blueoil/cmd/main.py
  blueoil/environment.py
  tests/unit/test_environment.py
Labels: CI: auto-run

#941 Support import of Sub operator
  blueoil/converter/core/operators.py
  blueoil/converter/plugins/tf.py
Labels: CI: auto-run

#364 Kernel Initializer issue
  blueoil/blocks.py
  blueoil/layers/layers.py
Labels: CI: auto-run

#754 Update default config for BDD100K dataset
  blueoil/configs/core/object_detection/lm_fyolo_bdd100k.py
Labels: CI: auto-run
