Repository blue-oil/blueoil, pull requests merged in 2020-04, with the labels that each got.

#963 Fix typo on darknet.py and lm_fyolo.py
  blueoil/networks/classification/darknet.py
  blueoil/networks/object_detection/lm_fyolo.py
Labels: CI: auto-run

#951 Avoid to use static constexpr member in C++14
  blueoil/converter/templates/include/tensor_view.h
Labels: CI: auto-run, bug

#919 Fix condition for threshold-skipping
  blueoil/converter/core/optimizer.py
Labels: CI: auto-run, bug

#967 Fix arg name in comment quantize to quantizer
  blueoil/networks/classification/darknet.py
  blueoil/networks/object_detection/lm_fyolo.py
  blueoil/networks/object_detection/yolo_v2_quantize.py
Labels: CI: auto-run

#846 Apply tfds pre processor
  blueoil/datasets/dataset_iterator.py
  blueoil/datasets/tfds.py
  blueoil/pre_processor.py
  blueoil/tfds_augmentor.py
  blueoil/tfds_data_processor.py
  blueoil/tfds_pre_processor.py
  blueoil/utils/config.py
  tests/unit/executor_tests/test_build_tfds.py
  tests/unit/fixtures/configs/for_build_tfds_classification.py
  tests/unit/fixtures/configs/for_build_tfds_object_detection.py
  tests/unit/test_tfds_augmentor.py
  tests/unit/test_tfds_pre_processor.py
Labels: CI: auto-run

#969 Rollback Sphinx version to 2.4.4
  docs/requirements.txt
Labels: CI: auto-run, documentation

#970 Update version of Pillow library to fix security problem
  output_template/python/requirements.txt
  setup.cfg
Labels: CI: auto-run

#913 Apply tf_upgrade_v2 for metrics
  blueoil/metrics/mean_average_precision.py
  blueoil/metrics/metrics.py
Labels: CI: auto-run

#972 Update setup.cfg to v0.22.0
  setup.cfg
Labels: CI: auto-run

#973 Remove an argument `type` from all `__getitem__` method
  blueoil/datasets/base.py
  blueoil/datasets/bdd100k.py
  blueoil/datasets/camvid.py
  blueoil/datasets/cifar10.py
  blueoil/datasets/cifar100.py
  blueoil/datasets/delta_mark.py
  blueoil/datasets/div2k.py
  blueoil/datasets/ilsvrc_2012.py
  blueoil/datasets/image_folder.py
  blueoil/datasets/mscoco.py
  blueoil/datasets/open_images_v4.py
  blueoil/datasets/pascalvoc_2007_2012.py
  blueoil/datasets/pascalvoc_base.py
  blueoil/datasets/widerface.py
Labels: CI: auto-run

#974 Refactor for consistency in blueoil/networks directory
  blueoil/networks/classification/base.py
  blueoil/networks/classification/darknet.py
  blueoil/networks/classification/lm_resnet.py
  blueoil/networks/classification/lmnet_v0.py
  blueoil/networks/classification/lmnet_v1.py
  blueoil/networks/classification/mobilenet_v2.py
  blueoil/networks/classification/vgg16.py
  blueoil/networks/keypoint_detection/lm_single_pose_v1.py
  blueoil/networks/object_detection/lm_fyolo.py
  blueoil/networks/object_detection/yolo_v1.py
  blueoil/networks/object_detection/yolo_v2.py
  blueoil/networks/object_detection/yolo_v2_quantize.py
  blueoil/networks/segmentation/base.py
  blueoil/networks/segmentation/lm_bisenet.py
  blueoil/networks/segmentation/lm_segnet_v0.py
  blueoil/networks/segmentation/lm_segnet_v1.py
Labels: CI: auto-run

#966 Add a simple network as a supplementary source code for how to quantize document.
  blueoil/networks/classification/quantize_example.py
  tests/unit/networks_tests/classification_test/test_example_quantize.py
Labels: CI: auto-run, documentation

#955 How to quantize document
  docs/_static/quantize_example_minimal_graph_with_shape.png
  docs/index.rst
  docs/quantize/activation_quantization.rst
  docs/quantize/index.rst
  docs/quantize/quantization_template.rst
  docs/quantize/weight_quantization.rst
Labels: CI: auto-run, documentation

#981 Fixed pep8 errors "F405" in converter
  blueoil/converter/__init__.py
  blueoil/converter/core/operators.py
  blueoil/converter/core/params.py
  blueoil/converter/core/view.py
Labels: CI: auto-run

#984 Fixed pep8 errors "F841" in converter
  blueoil/converter/core/view.py
  blueoil/converter/plugins/tf.py
  tests/converter/test_consistency_check.py
  tests/converter/test_operators.py
Labels: CI: auto-run

#983 Fixed pep8 errors "F401" in converter
  blueoil/converter/code_generator.py
  blueoil/converter/core/__init__.py
  blueoil/converter/core/graph.py
  blueoil/converter/core/operators.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/frontend/__init__.py
  tests/converter/test_code_generation.py
  tests/converter/test_consistency_check.py
  tests/converter/test_optimizer.py
  tests/converter/test_tf_io.py
  tests/converter/testcase_dlk_base.py
Labels: CI: auto-run

#985 Fixed pep8 errors about formatting
  blueoil/converter/core/graph_pattern_matching.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/generate_project.py
  blueoil/converter/modules/packer.py
  blueoil/converter/util.py
  tests/converter/test_binary.py
  tests/converter/test_code_generation.py
  tests/converter/test_generate_project.py
  tests/converter/tstconf.py
  tests/converter/tstutils.py
Labels: CI: auto-run

#976 Fix Blueoil init in the case of no validation dataset
  blueoil/cmd/init.py
Labels: CI: auto-run, bug

#978 Remove SSDRandomCrop augmentation from classification task tutorial.
  docs/tutorial/image_cls.md
Labels: CI: auto-run, documentation

#977 Remove validation dataset path from object detection tutorial document
  docs/tutorial/image_det.md
Labels: CI: auto-run, documentation

#987 Fixed pep8 errors about exceptions
  blueoil/converter/core/params.py
  blueoil/converter/plugins/tf.py
  tests/converter/test_code_generation.py
  tests/converter/tstutils.py
Labels: CI: auto-run

#994 Add __init__.py to the missing locations in blueoil/.
  blueoil/converter/utils/__init__.py
  blueoil/metrics/__init__.py
  blueoil/networks/keypoint_detection/__init__.py
  blueoil/networks/object_detection/__init__.py
  blueoil/utils/tfds_builders/__init__.py
Labels: CI: auto-run

#982 Change condition to show an warning from generate_project.py
  blueoil/converter/core/operators.py
  docs/converter/supported_ops.md
Labels: CI: auto-run

#986 Remove some code from time measurement
  output_template/python/run.py
Labels: CI: auto-run

#989 Remove error from make html doc and update converter doc using Sphinx-apidoc
  docs/converter/converter.core.rst
  docs/converter/converter.frontend.rst
  docs/converter/converter.plugins.rst
  docs/converter/converter.rst
  docs/converter/optimization.rst
Labels: CI: auto-run, bug, documentation

#988 Include converter in pep8 coverage
  Makefile
  blueoil/converter/core/view.py
Labels: CI: auto-run

#995 Create auto generate Python API document for `blueoil/` directory.
  docs/conf.py
  docs/converter/converter.core.rst
  docs/converter/converter.frontend.rst
  docs/converter/converter.modules.rst
  docs/converter/converter.plugins.rst
  docs/converter/converter.rst
  docs/converter/index.rst
  docs/converter/modules.rst
  docs/index.rst
  docs/reference/data_augmentor.rst
  docs/reference/index.rst
  docs/requirements.txt
Labels: CI: auto-run, dependencies, documentation, enhancement

#1005 Support TFDS format for segmentation
  blueoil/cmd/build_tfds.py
  blueoil/cmd/train.py
  blueoil/datasets/tfds.py
  blueoil/utils/tfds_builders/segmentation.py
  tests/unit/executor_tests/test_build_tfds.py
  tests/unit/fixtures/configs/for_build_tfds_segmentation.py
Labels: CI: auto-run, enhancement

#1004 Add table support in markdown (.md) file
  docs/conf.py
  docs/requirements.txt
Labels: CI: auto-run, dependencies, documentation, enhancement

#1008 Change available_subsets as a class variable
  blueoil/datasets/base.py
  blueoil/datasets/camvid.py
Labels: CI: auto-run

#999 Move global_step to network class
  blueoil/cmd/convert_weight_from_darknet.py
  blueoil/cmd/evaluate.py
  blueoil/cmd/train.py
  blueoil/cmd/tune_ray.py
  blueoil/networks/base.py
  blueoil/networks/object_detection/lm_fyolo.py
  blueoil/networks/object_detection/yolo_v1.py
  blueoil/networks/object_detection/yolo_v2.py
Labels: CI: auto-run

#1000 Add Network specification and update network code structure.
  docs/specification/network.md
  docs/specification/network_profile/LMFYoloQuantize_profile.md
  docs/specification/network_profile/LmSegnetV1Quantize_profile.md
  docs/specification/network_profile/LmnetV1Quantize_profile.md
Labels: CI: auto-run, documentation

#1013 Clean Up Makefile of Runtime
  blueoil/cmd/convert.py
  blueoil/converter/templates/Makefile
  tests/converter/test_binary.py
  tests/converter/test_code_generation.py
Labels: CI: auto-run

#1001 Fix a stability about multiple measurements
  output_template/python/run.py
Labels: CI: auto-run
