Repository blue-oil/blueoil, pull requests merged in 2020-08, with the labels that each got.

#1135 Fix comments typo in base.py
  blueoil/datasets/base.py
Labels: CI: auto-run, documentation

#1140 Enhance the dataset class to accept the dataset in PASCALVOC format with configuration.
  blueoil/datasets/pascalvoc_custom.py
Labels: CI: auto-run, enhancement

#1147 Update Raspberry-Pi CI env
  .buildkite/blueoil-pipeline.yml
  .buildkite/dlk-pipeline.yml
Labels: CI: auto-run

#1148 Make lint/type tests available without docker build
  .buildkite/lmnet-pipeline.yml
  Makefile
Labels: CI: auto-run

#1149 Add flake8 test to output_template
  Makefile
  output_template/python/motion_jpeg_server_from_camera.py
  output_template/python/run.py
  output_template/python/usb_camera_demo.py
Labels: CI: auto-run

#1151 Update dependencies
  .buildkite/blueoil-pipeline.yml
  output_template/python/requirements.txt
  setup.cfg
Labels: CI: auto-run

#1153 Remove make_os directory
  Makefile
  docker/Dockerfile_make_os
  make_os/README.md
  make_os/build/make_rootfs.sh
  make_os/build/setting_after_chroot.sh
Labels: CI: auto-run

#1150 Update Blueoil to v0.27.0
  setup.cfg
Labels: CI: auto-run

#1159 Fix argument order for Resize function
  runtime/include/blueoil_image.hpp
  runtime/src/blueoil_image.cpp
Labels: CI: auto-run

#1168 Fix absl-py version to 0.8.1
  setup.cfg
Labels: CI: auto-run, bug, dependencies

#1155 Add unittest CI environment for inference scripts (output_template)
  .buildkite/lmnet-pipeline.yml
  Makefile
  docker/Dockerfile-inference
  tests/output_template/test_run.py
Labels: CI: auto-run

#1166 Add unit test for PASCALVOC Dataset Loader classes
  tests/unit/datasets_tests/test_pascalvoc.py
  tests/unit/fixtures/datasets/PASCALVOC_2012/VOCdevkit/VOC2012/Annotations/2012_002012.xml
  tests/unit/fixtures/datasets/PASCALVOC_2012/VOCdevkit/VOC2012/ImageSets/Main/train.txt
  tests/unit/fixtures/datasets/PASCALVOC_2012/VOCdevkit/VOC2012/ImageSets/Main/trainval.txt
  tests/unit/fixtures/datasets/PASCALVOC_2012/VOCdevkit/VOC2012/ImageSets/Main/val.txt
  tests/unit/fixtures/datasets/PASCALVOC_2012/VOCdevkit/VOC2012/JPEGImages/2012_002012.jpg
Labels: CI: auto-run

#1172 Add dataset loader for FER2013 format
  blueoil/datasets/fer_2013.py
  tests/unit/datasets_tests/test_fer_2013.py
  tests/unit/fixtures/datasets/FER2013/test.csv
Labels: CI: auto-run

#1165 Change offsetVolume function
  runtime/src/blueoil.cpp
Labels: CI: auto-run

#1175 Enable coverage report in unit tests
  Makefile
  setup.cfg
  tests/unit/.coveragerc
Labels: CI: auto-run

#1179 Add export network trainable variables (PRETRAIN_VARS) to experiment dir
  blueoil/cmd/train.py
Labels: CI: auto-run

#1182 Update the link to the latest OS image
  docs/install/install.md
Labels: CI: auto-run

#1183 Add explanations about serial communication
  docs/install/install.md
Labels: CI: auto-run

#1177 Fix shapes and available_subset of FER2013 loader
  blueoil/datasets/fer_2013.py
  tests/unit/datasets_tests/test_fer_2013.py
Labels: CI: auto-run

#1187 Fix missing link in document
  docs/specification/config.md
  docs/usage/export.md
  docs/usage/init.md
Labels: CI: auto-run, documentation

#1163 Fix an error of runtime with no bounding box of object detection
  runtime/src/blueoil.cpp
Labels: CI: auto-run

#1186 Remove the unnecessary subset argument
  blueoil/datasets/fer_2013.py
Labels: CI: auto-run

#1185 Add a config file for FER2013
  blueoil/configs/core/classification/lmnet_v1_quantize_fer_2013.py
Labels: CI: auto-run

#1180 Fix document typo
  docs/usage/timing.md
Labels: CI: auto-run

#1161 Lookup without DivideBy255
  blueoil/cmd/convert.py
  blueoil/cmd/export.py
  blueoil/converter/core/config.py
  blueoil/converter/core/operators.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/core/view.py
  blueoil/converter/generate_project.py
  blueoil/converter/templates/include/func/lookup.h
  blueoil/converter/templates/src/func/lookup.cpp
Labels: CI: auto-run, enhancement
