Repository blue-oil/blueoil, pull requests merged in 2020-09, with the labels that each got.

#1190 Use g++-8 to keep consistency in each architecture
  docker/Dockerfile
Labels: CI: auto-run

#1146 Fix mypy errors: converter/core/operators.py
  blueoil/converter/core/operators.py
Labels: CI: auto-run

#1156 Python3 support of motion_jpeg_server_from_camera.py
  docker/Dockerfile-inference
  output_template/python/motion_jpeg_server_from_camera.py
  tests/output_template/test_motion_jpeg_server_from_camera.py
Labels: CI: auto-run

#1195 Fix MAX_STEPS = 0 error by add suggestion and exit
  blueoil/cmd/train.py
Labels: CI: auto-run

#1196 Update setup.cfg to v0.28.0
  setup.cfg
Labels: CI: auto-run

#1191 fix : Change time.clock to time.perf_counter
  output_template/python/usb_camera_demo.py
Labels: CI: auto-run

#1198 Remove xenial from test pipelines
  .buildkite/blueoil-pipeline.yml
  .buildkite/dlk-pipeline.yml
Labels: CI: auto-run

#1154 Update converter test to PY3 and drop py2 functions
  blueoil/common.py
  blueoil/post_processor.py
  blueoil/visualize.py
  output_template/python/blueoil/data_processor.py
  output_template/python/config.py
  output_template/python/lmnet/utils/demo.py
  output_template/python/motion_jpeg_server_from_camera.py
  output_template/python/requirements.txt
  output_template/python/usb_camera_demo.py
  tests/converter/test_code_generation.py
Labels: CI: auto-run

#1203 change the option name in export documentation to "image"
  docs/usage/export.md
Labels: CI: auto-run, documentation

#1207 Fix confitions not to use tfds_pre_processor and tfds_augumentor
  blueoil/datasets/dataset_iterator.py
Labels: CI: auto-run, bug

#1204 Add blueoil.io module for I/O with GCS support
  blueoil/io/__init__.py
  blueoil/io/file_io.py
  tests/unit/io_tests/test_file_io.py
Labels: CI: auto-run

#1202 change python to python3 in usage docs
  docs/usage/convert.md
  docs/usage/evaluate.md
  docs/usage/export.md
  docs/usage/init.md
  docs/usage/measure_latency.md
  docs/usage/predict.md
  docs/usage/profile_model.md
  docs/usage/train.md
Labels: CI: auto-run, documentation

#1197 Enable to save pretrain_vars.txt to GCS
  blueoil/cmd/train.py
Labels: CI: auto-run

#1212 Adding `--gpu={gpu index}` flag to docker option in tutorials.
  docs/tutorial/image_cls.md
  docs/tutorial/image_det.md
  docs/tutorial/image_keypoint_detection.md
  docs/tutorial/image_seg.md
Labels: CI: auto-run

#1214 rewrite error comparing
  blueoil/converter/templates/include/dlk_test.h
Labels: CI: auto-run

#1209 Avoid ValueError for TFDS with BBox on the last pixel
  blueoil/utils/tfds_builders/object_detection.py
Labels: CI: auto-run

#1206 Support evaluation with GCS I/O
  blueoil/cmd/evaluate.py
  blueoil/utils/config.py
  blueoil/utils/predict_output/writer.py
Labels: CI: auto-run

#1217 Consider that 'Reshape' won't preserve quantization
  blueoil/converter/core/operators.py
Labels: CI: auto-run, bug

#1215 Fix typo on the installation documentation
  docs/install/install.md
Labels: CI: auto-run, documentation

#1219 Remove output_event.py
  blueoil/cmd/output_event.py
  setup.cfg
  tests/unit/executor_tests/test_output_event.py
Labels: CI: auto-run

#1220 Replace EasyDict to SmartDict
  blueoil/cmd/tune_ray.py
  blueoil/configs/convert_weight_from_darknet/darknet19.py
  blueoil/configs/convert_weight_from_darknet/yolo_v2.py
  blueoil/configs/core/classification/darknet_cifar10.py
  blueoil/configs/core/classification/darknet_quantize_cifar10.py
  blueoil/configs/core/classification/darknet_quantize_ilsvrc_2012.py
  blueoil/configs/core/classification/lm_resnet_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_cifar10.py
  blueoil/configs/core/classification/lmnet_cifar100.py
  blueoil/configs/core/classification/lmnet_openimagesv4.py
  blueoil/configs/core/classification/lmnet_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_quantize_cifar100.py
  blueoil/configs/core/classification/lmnet_v1_cifar10.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10_tune.py
  blueoil/configs/core/classification/lmnet_v1_quantize_fer_2013.py
  blueoil/configs/core/classification/mobilenet_v2_cifar10.py
  blueoil/configs/core/classification/resnet_cifar10.py
  blueoil/configs/core/keypoint_detection/lm_single_pose_v1_quantize_mscoco.py
  blueoil/configs/core/object_detection/lm_fyolo_bdd100k.py
  blueoil/configs/core/object_detection/lm_fyolo_quantize_pascalvoc_2007_2012.py
  blueoil/configs/core/object_detection/yolo_v2_quantize_pascalvoc_2007_2012.py
  blueoil/configs/core/segmentation/lm_bisenet_quantize_camvid.py
  blueoil/configs/core/segmentation/lm_segnet_v0_quantize_camvid.py
  blueoil/configs/core/segmentation/lm_segnet_v1_quantize_camvid.py
  blueoil/configs/core/segmentation/segnet_camvid.py
  blueoil/configs/core/segmentation/segnet_quantize_bdd100k.py
  blueoil/configs/core/segmentation/segnet_quantize_camvid.py
  blueoil/configs/core/segmentation/segnet_quantize_camvid_tune.py
  blueoil/configs/core/segmentation/segnet_quantize_cityscapes.py
  blueoil/configs/example/classification.py
  blueoil/configs/example/object_detection.py
  blueoil/templates/lmnet/classification.tpl.py
  blueoil/templates/lmnet/keypoint_detection.tpl.py
  blueoil/templates/lmnet/object_detection.tpl.py
  blueoil/templates/lmnet/semantic_segmentation.tpl.py
  blueoil/utils/config.py
  blueoil/visualize.py
  output_template/python/config.py
  output_template/python/requirements.txt
  setup.cfg
  tests/unit/fixtures/configs/for_build_tfds_classification.py
  tests/unit/fixtures/configs/for_build_tfds_object_detection.py
  tests/unit/fixtures/configs/for_build_tfds_segmentation.py
  tests/unit/fixtures/configs/for_export.py
  tests/unit/fixtures/configs/for_predict_classification.py
  tests/unit/fixtures/configs/for_predict_object_detection.py
  tests/unit/fixtures/configs/for_profile.py
  tests/unit/fixtures/configs/for_train.py
  tests/unit/networks_tests/classification_test/test_darknet.py
  tests/unit/networks_tests/classification_test/test_example_quantize.py
  tests/unit/networks_tests/classification_test/test_lm_resnet_quantize.py
  tests/unit/networks_tests/classification_test/test_lmnet_quantize.py
  tests/unit/networks_tests/keypoint_detection_tests/test_lm_single_pose_v1.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v1.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v2.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v2_quantize.py
  tests/unit/networks_tests/segmentation_tests/test_lm_bisenet.py
  tests/unit/test_visualize.py
  tests/unit/util_tests/test_config.py
Labels: CI: auto-run

#1221 Update to v0.29.0
  setup.cfg
Labels: CI: auto-run

#1200 move keep_me.md(#937)
  blueoil/converter/templates/debug/.gitkeep
  docs/converter/debug.md
Labels: CI: auto-run

#1199 replace sprintf for ostringstream(#1192)
  blueoil/converter/templates/include/npy.hpp
Labels: CI: auto-run
