Repository blue-oil/blueoil, pull requests merged in 2020-03, with the labels that each got.

#869 Fix is_scalar
  blueoil/converter/core/operators.py
  blueoil/converter/generate_project.py
  blueoil/converter/plugins/tf.py
  blueoil/converter/templates/manual/consts/input.tpl.cpp
  blueoil/converter/templates/manual/consts/input.tpl.h
Labels: CI: auto-run, bug

#885 Update setup.cfg to v0.20.0
  setup.cfg
Labels: CI: auto-run

#875 tf_upgrade_v2 for cmd
  blueoil/cmd/convert_weight_from_darknet.py
  blueoil/cmd/evaluate.py
  blueoil/cmd/export.py
  blueoil/cmd/measure_latency.py
  blueoil/cmd/predict.py
  blueoil/cmd/profile_model.py
  blueoil/cmd/train.py
  blueoil/cmd/tune_ray.py
Labels: CI: auto-run

#887 Add blueoil.datasets as module
  blueoil/datasets/__init__.py
Labels: CI: auto-run

#890 Fix type annotation
  blueoil/converter/plugins/tf.py
Labels: CI: auto-run

#882 Migrate from whaaaaat to inquirer
  blueoil/cmd/init.py
  setup.cfg
Labels: CI: auto-run

#886 Fix LMBiSeNet inference (.elf) test error on x86 and DE10-Nano
  blueoil/networks/segmentation/lm_bisenet.py
Labels: CI: auto-run

#888 fix comparator for decreasing function of threshold skipping
  blueoil/converter/templates/src/func/impl/generic/apply_thresholds.cpp
Labels: CI: auto-run

#889 Fix output image results in Semantic Segmentation task from run.py
  blueoil/utils/predict_output/output.py
Labels: CI: auto-run

#878 Remove unused DLK readme files
  docs/dlk/README.md
  docs/dlk/auto_script.md
  docs/dlk/index.rst
  docs/dlk/overview.md
  docs/dlk/packages.md
  docs/dlk/policy.md
  docs/dlk/setup_board.md
  docs/dlk/shared_library.md
Labels: CI: auto-run, documentation

#683 Experimental support for 5x5 convolution on CPU
  blueoil/converter/templates/include/de10_nano.h
  blueoil/converter/templates/include/func/quantized_conv2d.h
  blueoil/converter/templates/include/matrix/shift_add.h
  blueoil/converter/templates/src/func/conv2d.cpp
  blueoil/converter/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  blueoil/converter/templates/src/func/impl/generic/quantized_conv2d_kn2row.cpp
  blueoil/converter/templates/src/func/impl/x86_avx/quantized_conv2d_tiling.cpp
  blueoil/converter/templates/src/matrix/shift_add.cpp
Labels: CI: auto-run

#893 Move lmnet/README.md to docs/usage and split it into each subcommand
  docs/usage/evaluate.md
  docs/usage/export.md
  docs/usage/measure_latency.md
  docs/usage/predict.md
  docs/usage/profile_model.md
  lmnet/README.md
Labels: CI: auto-run

#894 tf_upgrade_v2 for dataset
  blueoil/datasets/dataset_iterator.py
  blueoil/datasets/tfds.py
Labels: CI: auto-run

#905 Add docker build step at the beginning of all CI pipeline
  .buildkite/blueoil-pipeline.yml
  .buildkite/dlk-pipeline.yml
  .buildkite/lmnet-pipeline.yml
Labels: CI: auto-run

#900 Fix code generator typo
  blueoil/converter/code_generator.py
  blueoil/converter/generate_project.py
  docs/dlk/dlk.rst
Labels: CI: auto-run

#896 Update DLK -> Converter docs
  docs/converter/archive_file.md
  docs/converter/auto_script.md
  docs/converter/converter.core.rst
  docs/converter/converter.modules.rst
  docs/converter/converter.rst
  docs/converter/index.rst
  docs/converter/modules.rst
  docs/converter/optimization.rst
  docs/converter/overview.md
  docs/converter/shared_library.md
  docs/index.rst
Labels: CI: auto-run

#903 Update blueoil tutorial document to match blueoil r 0.20
  docs/tutorial/image_cls.md
  docs/tutorial/image_det.md
  docs/tutorial/image_keypoint_detection.md
  docs/tutorial/image_seg.md
Labels: CI: auto-run

#907 Remove PYTHONPATH
  docker-compose.yml
Labels: CI: auto-run

#899 tf_upgrade_v2 for configs
  blueoil/configs/core/classification/darknet_cifar10.py
  blueoil/configs/core/classification/darknet_quantize_cifar10.py
  blueoil/configs/core/classification/darknet_quantize_ilsvrc_2012.py
  blueoil/configs/core/classification/lm_resnet_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_cifar10.py
  blueoil/configs/core/classification/lmnet_cifar100.py
  blueoil/configs/core/classification/lmnet_openimagesv4.py
  blueoil/configs/core/classification/lmnet_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_quantize_cifar100.py
  blueoil/configs/core/classification/lmnet_v1_cifar10.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10_tune.py
  blueoil/configs/core/classification/mobilenet_v2_cifar10.py
  blueoil/configs/core/classification/resnet_cifar10.py
  blueoil/configs/core/keypoint_detection/lm_single_pose_v1_quantize_mscoco.py
  blueoil/configs/core/object_detection/lm_fyolo_bdd100k.py
  blueoil/configs/core/object_detection/lm_fyolo_quantize_pascalvoc_2007_2012.py
  blueoil/configs/core/object_detection/yolo_v2_quantize_pascalvoc_2007_2012.py
  blueoil/configs/core/segmentation/lm_bisenet_quantize_camvid.py
  blueoil/configs/core/segmentation/lm_segnet_v0_quantize_camvid.py
  blueoil/configs/core/segmentation/lm_segnet_v1_quantize_camvid.py
  blueoil/configs/core/segmentation/segnet_camvid.py
  blueoil/configs/core/segmentation/segnet_quantize_bdd100k.py
  blueoil/configs/core/segmentation/segnet_quantize_camvid.py
  blueoil/configs/core/segmentation/segnet_quantize_camvid_tune.py
  blueoil/configs/core/segmentation/segnet_quantize_cityscapes.py
  blueoil/configs/example/classification.py
  blueoil/configs/example/object_detection.py
Labels: CI: auto-run

#910 Update dependency packages
  setup.cfg
Labels: CI: auto-run

#891 Include types.h instead of global.h
  blueoil/converter/templates/include/dlk_test.h
  blueoil/converter/templates/include/func/add.h
  blueoil/converter/templates/include/func/average_pool.h
  blueoil/converter/templates/include/func/batch_normalization.h
  blueoil/converter/templates/include/func/concat_on_depth.h
  blueoil/converter/templates/include/func/depth_to_space.h
  blueoil/converter/templates/include/func/leaky_relu.h
  blueoil/converter/templates/include/func/matmul.h
  blueoil/converter/templates/include/func/max.h
  blueoil/converter/templates/include/func/max_pool.h
  blueoil/converter/templates/include/func/minimum.h
  blueoil/converter/templates/include/func/mul.h
  blueoil/converter/templates/include/func/pad.h
  blueoil/converter/templates/include/func/real_div.h
  blueoil/converter/templates/include/func/relu.h
  blueoil/converter/templates/include/func/resize_nearest_neighbor.h
  blueoil/converter/templates/include/func/softmax.h
  blueoil/converter/templates/include/func/sub.h
  blueoil/converter/templates/include/types.h
  blueoil/converter/templates/src/func/arm_neon/batch_normalization.cpp
  blueoil/converter/templates/src/func/generic/batch_normalization.cpp
  blueoil/converter/templates/src/func/matmul.cpp
  blueoil/converter/templates/src/func/max_pool.cpp
  blueoil/converter/templates/src/func/pad.cpp
  blueoil/converter/templates/src/func/softmax.cpp
  blueoil/converter/templates/src/func/x86_avx/batch_normalization.cpp
  blueoil/converter/templates/src/write_to_file.cpp
Labels: CI: auto-run

#902 convert tf2 for blueoil/generate_lmnet_config.py
  blueoil/generate_lmnet_config.py
Labels: CI: auto-run

#911 Update setup.cfg to v0.21.0
  setup.cfg
Labels: CI: auto-run

#918 Fix debug
  blueoil/converter/templates/src/network.tpl.cpp
Labels: CI: auto-run, bug

#914 Apply tf_upgrade_v2 for utils
  blueoil/utils/executor.py
Labels: CI: auto-run

#916 Apply tf_upgrade_v2 for output_template
  output_template/python/lmnet/tensorflow_graph_runner.py
Labels: CI: auto-run

#926 Fix very small comment typo
  blueoil/converter/core/operators.py
Labels: CI: auto-run

#925 Add Comment
  blueoil/converter/templates/src/network.tpl.cpp
Labels: CI: auto-run

#922 Add make commands
  Makefile
Labels: CI: auto-run

#932 Include the tests directory to flake8 targets
  Makefile
  tests/e2e/test_object_detection.py
  tests/unit/networks_tests/classification_test/test_lm_resnet_quantize.py
Labels: CI: auto-run

#930 Fix run.py time measurement log output
  output_template/python/run.py
Labels: CI: auto-run

#923 Update flake8 and fixed lint
  blueoil/cmd/output_event.py
  blueoil/datasets/base.py
  blueoil/datasets/mscoco.py
  blueoil/datasets/open_images_v4.py
  blueoil/datasets/pascalvoc_base.py
  blueoil/networks/base.py
  setup.cfg
Labels: CI: auto-run

#928 Add time measurement flag to all elf binaries in Makefile
  blueoil/cmd/convert.py
  blueoil/converter/templates/Makefile
Labels: CI: auto-run

#917 Fix threshold skipping if flg = -1
  blueoil/converter/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
Labels: CI: auto-run, bug

#920 Add Converter (DLK) limitation to blueoil
  docs/converter/index.rst
  docs/converter/supported_ops.md
Labels: CI: auto-run

#912 Fix comparison order in generationg thresholds
  blueoil/converter/core/optimizer.py
Labels: CI: auto-run, bug

#938 Fix checkpoint loader to use GFile
  blueoil/cmd/train.py
Labels: CI: auto-run

#944 Fix comment typo in __inin__.py in blueoil/blueoil/quantizations
  blueoil/quantizations/__init__.py
Labels: CI: auto-run

#943 Raise a FileNotFoundError when any config file does not exists
  blueoil/utils/config.py
Labels: CI: auto-run

#945 Fix softmax to avoid overflow
  blueoil/converter/templates/src/func/softmax.cpp
Labels: CI: auto-run, enhancement

#950 Report error and abort if channel size unmatch in ConcatOnDepth
  blueoil/converter/templates/include/func/concat_on_depth.h
Labels: CI: auto-run, enhancement

#670 Rename QTZ_linear_mid_tread_half
  blueoil/converter/core/operators.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/core/view.py
  blueoil/converter/plugins/tf.py
  blueoil/converter/templates/include/quantizer.h
  blueoil/converter/templates/src/quantizer.cpp
  blueoil/quantizations/linear.py
  docs/converter/supported_ops.md
  docs/usage/timing.md
  tests/converter/test_dynamic_create_op.py
  tests/converter/test_optimizer.py
Labels: CI: auto-run

#942 Improve readability of the predict script
  blueoil/cmd/predict.py
Labels: CI: auto-run

#845 Add divide 255 pre processor test
  tests/unit/test_pre_processor.py
Labels: CI: auto-run

#948 Remove a dataset subset type "train_validation_saving"
  blueoil/cmd/train.py
  blueoil/configs/core/classification/lmnet_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_quantize_cifar100.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10.py
  blueoil/configs/core/classification/lmnet_v1_quantize_cifar10_tune.py
  blueoil/datasets/base.py
  blueoil/datasets/cifar10.py
  blueoil/datasets/cifar100.py
  blueoil/datasets/dataset_iterator.py
Labels: CI: auto-run

#947 Remove graph output logic from training loop
  blueoil/cmd/train.py
Labels: CI: auto-run

#954 Add equation support for documentation generation
  docs/conf.py
Labels: CI: auto-run, documentation, enhancement

#936 Delete cmake dependency
  blueoil/converter/templates/CMakeLists.txt
  blueoil/converter/templates/cmake/config.cmake
  blueoil/converter/templates/cmake/toolchain/linux_aarch64.cmake
  blueoil/converter/templates/cmake/toolchain/linux_arm.cmake
  tests/converter/test_binary.py
  tests/converter/test_code_generation.py
Labels: CI: auto-run

#956 Update tensorflow-datasets version to 1.3.0
  blueoil/datasets/tfds.py
  blueoil/utils/tfds_builders/classification.py
  blueoil/utils/tfds_builders/object_detection.py
  setup.cfg
Labels: CI: auto-run

#957 Fix an issue which occurs invalid results with cache operation
  blueoil/converter/templates/include/dma_buffer.h
Labels: CI: auto-run

#958 Set yaml default Loader
  blueoil/cmd/train.py
Labels: CI: auto-run

#872 Add device inference test to e2e tests
  .buildkite/blueoil-pipeline.yml
  Makefile
  tests/device_tests/test_device_e2e.py
  tests/e2e/conftest.py
Labels: CI: auto-run

#959 Remove metrics placeholder from training loop
  blueoil/cmd/evaluate.py
  blueoil/cmd/train.py
  blueoil/utils/executor.py
Labels: CI: auto-run

#934 unpacking debug file for quantized tensor
  blueoil/converter/templates/Makefile
  blueoil/converter/templates/include/tensor_save.h
  blueoil/converter/templates/src/network.tpl.cpp
  blueoil/converter/templates/src/tensor_save.cpp
Labels: CI: auto-run, enhancement

#952 Add _save_json unit test for profile model
  tests/unit/executor_tests/test_profile.py
Labels: CI: auto-run
