Repository blue-oil/blueoil, pull requests merged in 2020-07, with the labels that each got.

#1113 One operator has at most one output
  blueoil/converter/core/operators.py
  blueoil/converter/core/view.py
  blueoil/converter/plugins/tf.py
  blueoil/converter/templates/include/func/slice.h
  blueoil/converter/templates/include/func/split.h
  blueoil/converter/templates/src/network.tpl.cpp
Labels: CI: auto-run

#1114 Fix limitation
  blueoil/converter/templates/src/func/average_pool.cpp
  blueoil/converter/templates/src/func/max_pool.cpp
  docs/converter/supported_ops.md
Labels: CI: auto-run, documentation

#1116 Remove unused functions: write_to_file
  blueoil/converter/templates/Makefile
  blueoil/converter/templates/include/global.tpl.h
  blueoil/converter/templates/src/write_to_file.cpp
Labels: CI: auto-run

#1117 Divide global.h into global.h and parameters.h
  blueoil/converter/templates/include/global.tpl.h
  blueoil/converter/templates/include/network.tpl.h
  blueoil/converter/templates/include/parameters.tpl.h
  blueoil/converter/templates/src/func/conv2d.cpp
  blueoil/converter/templates/src/func/impl/generic/quantized_conv2d_kn2row.cpp
  blueoil/converter/templates/src/func/impl/x86_avx/quantized_conv2d_tiling.cpp
  blueoil/converter/templates/src/network.tpl.cpp
Labels: CI: auto-run

#1118 Rename depth to channels
  blueoil/converter/core/operators.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/core/params.py
  blueoil/converter/core/view.py
  blueoil/converter/modules/packer.py
  blueoil/converter/plugins/tf.py
  blueoil/converter/templates/include/func/average_pool.h
  blueoil/converter/templates/include/func/concat_on_depth.h
  blueoil/converter/templates/include/func/depth_to_space.h
  blueoil/converter/templates/include/func/extract_image_patches.h
  blueoil/converter/templates/include/func/max_pool.h
  blueoil/converter/templates/include/func/quantized_conv2d.h
  blueoil/converter/templates/include/func/resize_nearest_neighbor.h
  blueoil/converter/templates/include/network.tpl.h
  blueoil/converter/templates/include/operators.h
  blueoil/converter/templates/include/pack_input_to_qwords.h
  blueoil/converter/templates/include/tensor_convert.h
  blueoil/converter/templates/manual/consts/scaling_factors.tpl.cpp
  blueoil/converter/templates/manual/consts/scaling_factors.tpl.h
  blueoil/converter/templates/manual/consts/thresholds.tpl.cpp
  blueoil/converter/templates/manual/consts/thresholds.tpl.h
  blueoil/converter/templates/src/func/arm_neon/batch_normalization.cpp
  blueoil/converter/templates/src/func/average_pool.cpp
  blueoil/converter/templates/src/func/conv2d.cpp
  blueoil/converter/templates/src/func/generic/batch_normalization.cpp
  blueoil/converter/templates/src/func/impl/arm_neon/quantized_conv2d_tiling.cpp
  blueoil/converter/templates/src/func/impl/fpga/quantized_conv2d_accelerator.cpp
  blueoil/converter/templates/src/func/impl/generic/quantized_conv2d_kn2row.cpp
  blueoil/converter/templates/src/func/impl/x86_avx/quantized_conv2d_tiling.cpp
  blueoil/converter/templates/src/func/lookup.cpp
  blueoil/converter/templates/src/func/matmul.cpp
  blueoil/converter/templates/src/func/max_pool.cpp
  blueoil/converter/templates/src/func/pad.cpp
  blueoil/converter/templates/src/func/x86_avx/batch_normalization.cpp
  blueoil/converter/templates/src/network.tpl.cpp
  blueoil/converter/templates/src/pack_input_to_qwords.cpp
  blueoil/converter/templates/src/quantizer.cpp
  blueoil/converter/templates/src/tensor_save.cpp
  tests/converter/test_operators.py
Labels: CI: auto-run

#1055 Add turbo color map
  blueoil/common.py
  blueoil/turbo_color_map.py
  output_template/python/blueoil/turbo_color_map.py
Labels: CI: auto-run

#1124 Fix config specification table layout
  docs/specification/config.md
Labels: CI: auto-run, documentation

#1122 FIx to set correct gs:// path
  blueoil/environment.py
  tests/unit/test_environment.py
Labels: CI: auto-run

#1125 Change a default bit of profiling
  blueoil/cmd/profile_model.py
Labels: CI: auto-run

#1126 Release v0.26.0
  setup.cfg
Labels: CI: auto-run

#1119 Insert Cast operator automatically
  blueoil/converter/core/operators.py
  blueoil/converter/core/optimizer.py
  blueoil/converter/core/view.py
  blueoil/converter/generate_project.py
  blueoil/converter/templates/Makefile
  blueoil/converter/templates/include/func/cast.h
  blueoil/converter/templates/src/func/cast.cpp
  blueoil/converter/templates/src/network.tpl.cpp
  tests/converter/test_optimizer.py
Labels: CI: auto-run, bug

#1127 Add minimum package installation and network settings to rootfs setup scripts
  Makefile
  make_os/README.md
  make_os/build/make_rootfs.sh
  make_os/build/setting_after_chroot.sh
Labels: CI: auto-run

#1133 Add blank line between copyright header and code
  blueoil/layers/__init__.py
  blueoil/networks/classification/__init__.py
  blueoil/networks/classification/lmnet/__init__.py
  blueoil/networks/classification/lmnet_quantize/__init__.py
  blueoil/networks/segmentation/__init__.py
  blueoil/networks/segmentation/lm_segnet/__init__.py
  blueoil/networks/segmentation/lm_segnet_quantize/__init__.py
Labels: CI: auto-run

#1130 Add DE10-nano bionic test env
  .buildkite/dlk-pipeline.yml
Labels: CI: auto-run

#1132 Add gitattribute to exclude files from archive
  .gitattributes
Labels: CI: auto-run

#1138 Switch main test DE10-Nano OS to bionic
  .buildkite/blueoil-pipeline.yml
  .buildkite/dlk-pipeline.yml
Labels: CI: auto-run

#1137 capitalize help messages
  blueoil/cmd/main.py
Labels: CI: auto-run

#1072 As for issue #484: remove pandas dependency
  blueoil/cmd/output_event.py
  blueoil/datasets/camvid.py
  blueoil/datasets/ilsvrc_2012.py
  blueoil/datasets/pascalvoc_2007.py
  blueoil/datasets/pascalvoc_base.py
  setup.cfg
Labels: CI: auto-run

#1141 CI: Add mypy test
  .buildkite/lmnet-pipeline.yml
  Makefile
  setup.cfg
Labels: CI: auto-run

#1139 Upgrade OS version to bionic for Docker image
  .buildkite/blueoil-pipeline.yml
  Makefile
  docker/Dockerfile
  docs/install/install.md
  output_template/python/README.md
  output_template/python/requirements.txt
Labels: CI: auto-run
