Repository blue-oil/blueoil, pull requests merged in 2020-06, with the labels that each got.

#1060 Added resample option to resize processors.
  blueoil/configs/example/classification.yaml
  blueoil/configs/example/classification_meta.yaml
  blueoil/configs/example/object_detection.yaml
  blueoil/configs/example/object_detection_meta.yaml
  blueoil/pre_processor.py
Labels: CI: auto-run

#1050 Update PYTHONPATH for main.py in document
  docs/usage/convert.md
  docs/usage/init.md
  docs/usage/train.md
Labels: CI: auto-run, documentation

#1056 Added test_image option to convert command.
  blueoil/cmd/convert.py
  blueoil/cmd/main.py
Labels: CI: auto-run

#1073 tf_upgrade_v2 for network/classification/base.py
  blueoil/networks/classification/base.py
Labels: CI: auto-run

#1074 tf_upgrade_v2 network/darknet.py
  blueoil/networks/classification/darknet.py
Labels: CI: auto-run

#1075 tf_upgrade_v2 for network/classification/lmnet_v0.py
  blueoil/networks/classification/lmnet_v0.py
Labels: CI: auto-run

#1045 Missing outputs of input placeholder
  blueoil/converter/core/optimizer.py
Labels: CI: auto-run

#1067 tf_upgrade_v2 for network/base.py
  blueoil/networks/base.py
Labels: CI: auto-run

#1077 tf_upgrade_v2 for keypoint_detection
  blueoil/networks/keypoint_detection/base.py
  blueoil/networks/keypoint_detection/lm_single_pose_v1.py
Labels: CI: auto-run

#1064 Rewrote config module for inference.
  output_template/python/config.py
Labels: CI: auto-run

#1069 tf_upgrade_v2 for network/classification/resnet.py
  blueoil/networks/classification/resnet.py
Labels: CI: auto-run

#1068 Processing has been optimized and speed has been improved.
  blueoil/converter/nnlib.py
Labels: CI: auto-run

#1071 Refactor cpp code
  blueoil/converter/templates/src/func/softmax.cpp
  blueoil/converter/templates/src/time_measurement.cpp
  blueoil/converter/templates/src/write_to_file.cpp
Labels: CI: auto-run

#1034 Change colormap scope
  blueoil/common.py
Labels: CI: auto-run

#1082 Remove YouTube Faces format from keypoint detection tutorial.
  docs/tutorial/image_keypoint_detection.md
Labels: CI: auto-run, documentation

#1083 Use time.time/time.perf_counter instead of time.clock for demo scripts
  output_template/python/lmnet/utils/demo.py
Labels: CI: auto-run

#1085 Fix checking pad
  blueoil/converter/core/operators.py
  tests/converter/test_consistency_check.py
Labels: CI: auto-run, bug

#1087 Avoid Error when debug dir didn't exist
  blueoil/converter/templates/src/network.tpl.cpp
Labels: CI: auto-run, bug

#1088 Update setup.cfg to v0.24.0
  setup.cfg
Labels: CI: auto-run

#1080 tf_upgrade_v2 for networks/classification/quantize_example.py
  blueoil/networks/classification/quantize_example.py
Labels: CI: auto-run

#1098 remove util functions that are no longer used
  blueoil/utils/config.py
Labels: CI: auto-run

#1063 Support FPGA with aarch64
  .buildkite/dlk-pipeline.yml
  Makefile
  blueoil/cmd/convert.py
  blueoil/converter/templates/Makefile
  blueoil/converter/templates/include/global.tpl.h
  tests/converter/test_code_generation.py
  tests/e2e/conftest.py
Labels: CI: auto-run, enhancement

#1100 Check stride and dilation >0
  blueoil/converter/core/operators.py
Labels: CI: auto-run, enhancement

#1106 Fix documents for new Makefile
  docs/converter/archive_file.md
  docs/converter/shared_library.md
Labels: CI: auto-run

#1109 Report maximum diff
  blueoil/converter/templates/include/dlk_test.h
Labels: CI: auto-run, enhancement

#1094 Implemented easydict.
  blueoil/utils/smartdict.py
  tests/unit/util_tests/test_smartdict.py
Labels: CI: auto-run

#1099 Update tutorials to use CPU in converting step
  docs/tutorial/image_cls.md
  docs/tutorial/image_det.md
  docs/tutorial/image_keypoint_detection.md
  docs/tutorial/image_seg.md
Labels: CI: auto-run

#1112 Update to v0.25.0
  setup.cfg
Labels: CI: auto-run

#1086 remove delta-mark files
  blueoil/datasets/delta_mark.py
  blueoil/generate_lmnet_config.py
  docs/usage/dataset.md
  tests/e2e/test_classification.py
  tests/e2e/test_object_detection.py
  tests/unit/datasets_tests/test_delta_mark.py
  tests/unit/executor_tests/test_build_tfds.py
  tests/unit/fixtures/configs/for_build_tfds_classification.py
  tests/unit/fixtures/configs/for_build_tfds_object_detection.py
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_train/images/1.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_train/images/2.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_train/images/3.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_train/json/annotation.json
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_validation/images/4.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_validation/images/5.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_classification/for_validation/json/annotation.json
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_train/images/1.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_train/images/2.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_train/images/3.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_train/json/annotation.json
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_validation/images/4.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_validation/images/5.jpg
  tests/unit/fixtures/datasets/custom_delta_mark_object_detection/for_validation/json/annotation.json
Labels: CI: auto-run

#1111 Profiler for training (memory and time per operation) of one train step
  blueoil/cmd/main.py
  blueoil/cmd/train.py
  blueoil/utils/executor.py
  docs/usage/train.md
  tests/unit/executor_tests/test_build_tfds.py
  tests/unit/executor_tests/test_export.py
  tests/unit/executor_tests/test_predict.py
  tests/unit/executor_tests/test_profile.py
  tests/unit/executor_tests/test_train.py
  tests/unit/networks_tests/classification_test/test_darknet.py
  tests/unit/networks_tests/classification_test/test_example_quantize.py
  tests/unit/networks_tests/classification_test/test_lm_resnet_quantize.py
  tests/unit/networks_tests/classification_test/test_lmnet_quantize.py
  tests/unit/networks_tests/keypoint_detection_tests/test_lm_single_pose_v1.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v1.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v2.py
  tests/unit/networks_tests/object_detection_tests/test_yolo_v2_quantize.py
  tests/unit/networks_tests/segmentation_tests/test_lm_bisenet.py
  tests/unit/util_tests/test_executor.py
Labels: CI: auto-run
