Repository blue-oil/blueoil, pull requests merged in 2021-02, with the labels that each got.

#1233 Fix docstring and documentation typo.
  blueoil/quantizations/binary.py
  blueoil/quantizations/linear.py
  docs/quantize/activation_quantization.rst
  docs/quantize/weight_quantization.rst
Labels: CI: auto-run, documentation

#1235 Fix sign function to return only 1 and -1
  blueoil/converter/core/operators.py
  blueoil/quantizations/binary.py
Labels: CI: auto-run, bug

#1237 Fix license texts for third-party code
  blueoil/common.py
  blueoil/data_augmentor.py
  blueoil/metrics/mean_average_precision.py
  blueoil/turbo_color_map.py
Labels: CI: auto-run

#1236 Version up docker image for deploying docs
  .circleci/config.yml
Labels: CI: auto-run

#1232 Use specified GPU in distributed training
  blueoil/cmd/train.py
  blueoil/datasets/tfds.py
Labels: CI: auto-run
